name 'rubyblock'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures rubyblock'
long_description 'Installs/Configures rubyblock'
version '0.1.0'
